/** @type {import('tailwindcss').Config} */
module.exports = {
  content: [
    "./src/**/*.{js,jsx,ts,tsx}", // Ensure this matches your project's file structure
  ],
  darkMode: 'media', // or 'class' for manual dark mode toggle
  theme: {
    extend: {
      colors: {
        green1: '#f2fbf2',
        green2: '#e1f7e1',
        green3: '#c4eec4',
        green4: '#82d982',
        green5: '#60c860',
        green6: '#3bac3c',
        green7: '#2b8e2c',
        green8: '#257026',
        green9: '#225923',
        green10: '#1e491f',
        green11: '#0b280d',
        primary: '#3490dc',
        secondary: '#ffed4a',
        accent: '#38c172',
        background: '#fffff',
        text: '#333',
        muted: '#6c757d',
        danger: '#e3342f',
        warning: '#f6993f',
        success: '#38c172',
        info: '#6cb2eb',
      },
      fontFamily: {
        sans: ['Inter', 'Sans-serif'],
        serif: ['Merriweather', 'Serif'],
        mono: ['Menlo', 'Monaco', 'Courier New', 'monospace'],
      },
      spacing: {
        '128': '32rem',
        '144': '36rem',
      },
      borderRadius: {
        'none': '0',
        'sm': '0.125rem',
        'default': '0.25rem',
        'md': '0.375rem',
        'lg': '0.5rem',
        'xl': '1rem',
        '2xl': '2rem',
        '3xl': '3rem',
        'full': '9999px',
      },
      boxShadow: {
        sm: '0 1px 2px 0 rgba(0, 0, 0, 0.05)',
        default: '0 1px 3px 0 rgba(0, 0, 0, 0.1), 0 1px 2px 0 rgba(0, 0, 0, 0.06)',
        md: '0 4px 6px -1px rgba(0, 0, 0, 0.1), 0 2px 4px -1px rgba(0, 0, 0, 0.06)',
        lg: '0 10px 15px -3px rgba(0, 0, 0, 0.1), 0 4px 6px -2px rgba(0, 0, 0, 0.05)',
        xl: '0 20px 25px -5px rgba(0, 0, 0, 0.1), 0 10px 10px -5px rgba(0, 0, 0, 0.04)',
        '2xl': '0 25px 50px -12px rgba(0, 0, 0, 0.25)',
        'inner': 'inset 0 2px 4px 0 rgba(0, 0, 0, 0.06)',
        'outline': '0 0 0 3px rgba(66, 153, 225, 0.5)',
        'none': 'none',
        'soft': '0 4px 6px rgba(0, 0, 0, 0.1)',
      },
      transitionProperty: {
        'none': 'none',
        'all': 'all',
        'default': 'background-color, border-color, color, fill, stroke, opacity, box-shadow, transform',
        'colors': 'background-color, border-color, color, fill, stroke',
        'opacity': 'opacity',
        'shadow': 'box-shadow',
        'transform': 'transform',
      },
      transitionTimingFunction: {
        'linear': 'linear',
        'in': 'cubic-bezier(0.4, 0, 1, 1)',
        'out': 'cubic-bezier(0, 0, 0.2, 1)',
        'in-out': 'cubic-bezier(0.4, 0, 0.2, 1)',
      },
      transitionDelay: {
        '75': '75ms',
        '100': '100ms',
        '150': '150ms',
        '200': '200ms',
        '300': '300ms',
        '500': '500ms',
        '700': '700ms',
        '1000': '1000ms',
      },
      screens: {
        'xs': '480px', // Custom extra small screen
        '3xl': '1920px', // Custom extra large screen
      },
      animation: {
        'spin-slow': 'spin 3s linear infinite',
        'ping-slow': 'ping 2s cubic-bezier(0, 0, 0.2, 1) infinite',
      },
      container: {
        center: true,
        padding: '2rem',
      },
      inset: {
        '1/2': '50%',
      },
      zIndex: {
        '60': '60',
      },
      // Button Variants
      button: {
        'primary': 'bg-primary text-white px-4 py-2 rounded hover:bg-primary-dark transition',
        'secondary': 'bg-secondary text-black px-4 py-2 rounded hover:bg-secondary-dark transition',
        'accent': 'bg-accent text-white px-4 py-2 rounded hover:bg-accent-dark transition',
        'outline': 'bg-transparent border-2 border-primary text-primary px-4 py-2 rounded hover:bg-primary hover:text-white transition',
        'disabled': 'bg-muted text-white px-4 py-2 rounded cursor-not-allowed opacity-50',
      },
    },
  },
  variants: {
    extend: {
      backgroundColor: ['responsive', 'hover', 'focus', 'active', 'disabled'],
      textColor: ['responsive', 'hover', 'focus', 'active', 'disabled'],
      borderColor: ['responsive', 'hover', 'focus', 'active', 'disabled'],
      opacity: ['responsive', 'hover', 'focus', 'disabled'],
      cursor: ['responsive', 'hover', 'focus', 'disabled'],
      display: ['responsive', 'group-hover'],
      visibility: ['responsive', 'group-hover'],
      zIndex: ['responsive', 'hover', 'focus'],
      scale: ['responsive', 'hover', 'focus', 'active', 'group-hover'],
      rotate: ['responsive', 'hover', 'focus', 'active', 'group-hover'],
      translate: ['responsive', 'hover', 'focus', 'active', 'group-hover'],
      skew: ['responsive', 'hover', 'focus', 'active', 'group-hover'],
      backgroundImage: ['responsive', 'hover', 'focus'],
      gradientColorStops: ['responsive', 'hover', 'focus'],
      backgroundOpacity: ['responsive', 'hover', 'focus'],
      borderOpacity: ['responsive', 'hover', 'focus'],
      textOpacity: ['responsive', 'hover', 'focus'],
      ringWidth: ['responsive', 'hover', 'focus', 'active'],
      ringColor: ['responsive', 'hover', 'focus', 'active'],
      ringOpacity: ['responsive', 'hover', 'focus', 'active'],
      ringOffsetWidth: ['responsive', 'hover', 'focus', 'active'],
      ringOffsetColor: ['responsive', 'hover', 'focus', 'active'],
      inset: ['responsive', 'hover', 'focus', 'group-hover'],
    },
  },
  plugins: [
    require('@tailwindcss/typography'),
    require('@tailwindcss/forms'),
    require('@tailwindcss/aspect-ratio'),
  ],
};